### ISSUE TITLE
Does not support tabs indentation

### ISSUE THREAD

**Issue by fedulvtubudul** [aheze/Multiliner#11]
If I indent with spaces:

![spaces_1](https://user-images.githubusercontent.com/635501/177246196-791c91ff-cb71-488a-9fa9-53ef7ec88e1e.png)

result is OK:

![spaces_2](https://user-images.githubusercontent.com/635501/177246201-303ee3c5-d43d-4963-8644-1867f9ff05e2.png)

But when tabs are used:

![tabs_1](https://user-images.githubusercontent.com/635501/177246346-8d7dccdd-2fc6-431b-9124-6c2184d09994.png)

result is just a mess of tabs and spaces (which is never correct):

![tabs_2](https://user-images.githubusercontent.com/635501/177246400-d6ee97e0-bb87-4f80-8bd6-99288a31bf4d.png)

**Comment by fedulvtubudul** [comment]
Probably `invocation.buffer.usesTabsForIndentation` should be checked. Now it seems to be ignored, as you always generate the `tab` this way: `let tab = String(repeating: " ", count: invocation.buffer.indentationWidth)`.

**Comment by aheze** [comment]
Thanks for report, will try `let tab = String(repeating: " ", count: invocation.buffer.indentationWidth)` and see if it works!

**Comment by aheze** [comment]
@fedulvtubudul fixed in 1.1! https://github.com/aheze/Multiliner/releases/tag/1.1.0
