### ISSUE TITLE
Support for brew

### ISSUE THREAD

**Issue by ztepsa** [aheze/Multiliner#12]
It would be nice to have an ability to install app using brew instead of having to do it manually. 
What do you think?

p.s. awesome idea for an extension 🎉

**Comment by aheze** [comment]
Hmm yeah then you could get auto-updates too. Will look into it, thanks for the suggestion!

**Comment by zeroid1** [comment]
> It would be nice to have an ability to install app using brew instead of having to do it manually. 
> What do you think?
> 
> p.s. awesome idea for an extension 🎉
