### ISSUE TITLE
App won't install

### ISSUE THREAD

**Issue by ddaddy** [aheze/Multiliner#13]
I had v1.0 installed and working, however since installing v1.1 the `Xcode Source Editor` section of the `System`->`Extensions` has disappeared, as if there are no extensions.

I've tried reinstalling v1.0 and it's the same 🤷‍♂️

Is there an additional step needed?

**Comment by aheze** [comment]
Hmm, have you opened the app first?

**Comment by ddaddy** [comment]
Yes.
I've downloaded the app from the link in the ReadMe.
Unzipped it.
Dragged it to my Applications folder.
Double click to open.
Confirm the "Downloaded from the internet" open prompt.
App Opens.
Open Settings and click Extensions.

There is no `Xcode source editor` listed.

I did notice the previous version was named `Multiliner App.app` but this one is just `Multiliner.app`. Not sure if that matters.

**Comment by brettohland** [comment]
@ddaddy There's some sort of system-wide bug with Xcode and its extensions that you've hit. I have this happen all of the time and I can usually fix it by doing the following:

1. Quit Xcode
2. Go to the `/Applications` directory
3. Rename Xcode to something (I usually just add a space character before the extension)
4. Rename Xcode back
5. Your extensions reappear

It's strange, but it works.

**Comment by aheze** [comment]
@ddaddy also maybe try deleting all copies of Multiliner if they exist — I had a bunch from testing. After deleting all copies the Source Editor tab disappeared, then after redownloading the app it appeared again. 

Lots of Multiliners | System Preferences (after redownloading)
--- | ---
<img width="1072" alt="Screen Shot 2022-07-06 at 10 44 23 AM" src="https://user-images.githubusercontent.com/49819455/177611896-32cb4e76-283b-4a0e-b16d-960bc2ce3d39.png"> | <img width="780" alt="Screen Shot 2022-07-06 at 10 48 09 AM" src="https://user-images.githubusercontent.com/49819455/177612105-774634c0-c2fd-404f-8fcd-639dbb9cf3d7.png">

**Comment by aheze** [comment]
Great, thanks @brettohland for the tips!

**Comment by brettohland** [comment]
🎉
