### ISSUE TITLE
Update built-in docs

### ISSUE THREAD

**Issue by orchetect** [aheze/Multiliner#16]
I just noticed that the GitHub docs / App Built-In Docs are out of sync.

- GitHub README shows setting up a Key Binding in Xcode,
- built-in docs of the MultilinerExtension app shows setting up an App Shortcut in System Preferences

Cheers, and thanks for your hard work

**Comment by orchetect** [comment]
Ah, just found it. I thought for a second that you were using the markdown rendering in SwiftUI but the built-in docs are literally just SwiftUI code. 😅

[Sources/Multiliner/ContentView.swift](https://github.com/aheze/Multiliner/blob/main/Sources/Multiliner/ContentView.swift)

```swift
Group {
    Text("3. To make this extension easier to reach, consider adding an App Shortcut in system preferences.")
        .font(.title3)

    Image("UsageShortcut")
        .resizable()
        .aspectRatio(contentMode: .fit)
}
```

**Comment by orchetect** [comment]
I can update and pull request.

**Comment by aheze** [comment]
Hey, thanks for the PR! Yeah the app is outdated right now... actually both the README and the app are old. Personally I prefer setting the shortcut in System Prefs, but maybe Xcode is easier — what do you think?

<img width="780" alt="Screen Shot 2022-07-09 at 11 38 17 AM" src="https://user-images.githubusercontent.com/49819455/178118740-214850f4-7a34-40fa-978c-3eeca0e2d14c.png">

**Comment by aheze** [comment]
Thanks for adding the gitignore btw!

**Comment by orchetect** [comment]
I think my gut instinct is 1) go for consistency and 2) since Xcode natively offers key bindings, that's probably where most people would be setting it.

**Comment by aheze** [comment]
Aight makes sense
