### ISSUE TITLE
Idea: Automatically determine scope?

### ISSUE THREAD

**Issue by calimarkus** [aheze/Multiliner#2]
I just saw this:

https://github.com/aheze/Multiliner/blob/150c4a99e37470c49eb3b2b6e7a6417946ba9f40/Sources/MultilinerExtension/SourceEditorCommand.swift#L21

It'd be cool, if you could only place the cursor in a scope and then it figures out the smallest matching scope that can apply?

**Comment by aheze** [comment]
Hmm that would be nice. Maybe a while loop or something?

**Comment by calimarkus** [comment]
Actually the command already achieves what I was thinking of. You only need to put the cursor and run the command. I wrongly assumed at first that you need to select the exact selection first.

What did you think of?
