### ISSUE TITLE
Multiliner not showing up in Extensions

### ISSUE THREAD

**Issue by tristanbiesecker** [aheze/Multiliner#21]
Despite having Multiliner (1.1.0) installed, it simply won't show up in System Settings -> Extensions. I've uninstalled, re-installed, restarted, etc. I'm running macOS 12.5 with Xcode 13.3.1.

<img width="683" alt="Screen Shot 2022-08-12 at 9 38 55 AM" src="https://user-images.githubusercontent.com/12146879/184404357-b24d7247-a578-44ab-a4cb-1a64666390f3.png">

**Comment by tristanbiesecker** [comment]
Ah, the solution was to rename Xcode and name it back. Now Multiliner is showing up properly.

**Comment by aheze** [comment]
Great! Similar issue: https://github.com/aheze/Multiliner/issues/13
