### ISSUE TITLE
Doesn't appear in Menu Editor

### ISSUE THREAD

**Issue by jdev7** [aheze/Multiliner#4]
I have installed the extension, and it doesn't appear in the Xcode menu editor.

I'm using Xcode 13.1, and I also have installed Xcode 13.3

I've tried several things such as the ones described here:

- https://stackoverflow.com/a/67679577/3708095
- https://github.com/nicklockwood/SwiftFormat/issues/494
- https://stackoverflow.com/a/58616132/3708095

But nothing worked, maybe it has something to do with:
https://stackoverflow.com/a/39472470/3708095
??

**Comment by AnthonyMDev** [comment]
Having the same issue. Hope someone can figure this out soon. I'd love to use this extension!

Have you considered submitting it to the app store as an Xcode Extension?

**Comment by NachoSoto** [comment]
I tried uninstalling, closing Xcode, opening the app again, re-adding the extension.... still nothing.
I'm on Xcode 14 beta 2 and macOS 13.0 beta 2.

**Comment by aheze** [comment]
Signing and notarizing... never done this before, hope it works!

<img width="1135" alt="Uploading to app store" src="https://user-images.githubusercontent.com/49819455/176317483-0b8c3e63-84fa-4379-93ac-9311aa2fdc59.png">

**Comment by aheze** [comment]
@jdev7, @AnthonyMDev, @NachoSoto I've re-signed and notarized the app, it should work now! Let me know if it's still broken. [Download zip](https://github.com/aheze/Multiliner/raw/main/Multiliner%20App.zip)

**Comment by jdev7** [comment]
It now  worked for me :)
