### ISSUE TITLE
How to use with macOS 13 Ventura & Xcode 14

### ISSUE THREAD

**Issue by trozware** [aheze/Multiliner#5]
Not an issue as I worked it out, but I thought others might look here to see how to enable this with the new System Settings app in macOS 13 Ventura.

- Close Xcode & System Settings
- Open the Multiliner app
- Open System Settings
- Go to Privacy & Security
- Scroll down to the end and click Extensions
- Click Xcode Source Editor and make sure Multiliner is toggled on

Now the option appears in the Xcode's Editor menu.

**Comment by aheze** [comment]
Nice, thanks for sharing!

**Comment by trozware** [comment]
Thank you for creating it. A very useful extension.
