### ISSUE TITLE
Does not show up in Extensions on macOS 12.4

### ISSUE THREAD

**Issue by guidedways** [aheze/Multiliner#7]
I've followed your instructions, however it does not seem to show up under Extensions on macOS 12.4

**Comment by aheze** [comment]
Hmm, have you opened the app first? Also it's possible that you downloaded the old, unsigned version of the app — try the notarized version: [`https://github.com/aheze/Multiliner/raw/main/Multiliner%20App.zip`](https://github.com/aheze/Multiliner/raw/main/Multiliner%20App.zip)

**Comment by guidedways** [comment]
Perfect, that worked. I downloaded the one from the main page and that did not work.
