### ISSUE TITLE
Preserve caret position after multi-lining selection

### ISSUE THREAD

**Issue by alobaili** [aheze/Multiliner#9]
Currently, when using Multiliner to multi-line selection, the caret moves to the end of the file. When undoing, the whole file text is selected.

It would be great if the caret stays after the closing bracket of the formatted code.

I love this extension. Thank you for amazing work!

**Comment by aheze** [comment]
Yeah I came across this too, would be a great improvement. Thanks for creating an issue for it! I'll look into it

**Comment by ccjensen** [comment]
I was just coming here to report this same issue. Love the extension, and I am willing to live with the caret position getting moved but a fix for this would be the cherry on top 😄

**Comment by aheze** [comment]
@ccjensen fixed in 1.1! https://github.com/aheze/Multiliner/releases/tag/1.1.0
